#!/usr/bin/env python3
"""
Volto Team Report Generator

Generates a markdown report of Volto team contributor statistics
across multiple time periods.
"""

import pandas as pd
from pathlib import Path
from datetime import datetime


def load_year(year):
    filepath = Path(f"data/{year}-volto-team-stats.csv")
    if not filepath.exists():
        return None
    try:
        df = pd.read_csv(filepath)
        df['year'] = year
        return df
    except Exception:
        return None


def combine(years):
    frames = [load_year(y) for y in years]
    frames = [f for f in frames if f is not None]
    if not frames:
        return None
    combined = pd.concat(frames).groupby('github_username').agg(
        {'pull_requests': 'sum', 'commits': 'sum'}
    ).reset_index()
    return combined.sort_values('pull_requests', ascending=False)


def format_number(n):
    return f"{int(n):,}"


def table(df):
    lines = []
    lines.append("| Rank | Contributor | PRs | Commits |")
    lines.append("|------|-------------|-----|---------|")
    for i, (_, row) in enumerate(df.iterrows(), 1):
        lines.append(
            f"| {i} | {row['github_username']} "
            f"| {format_number(row['pull_requests'])} "
            f"| {format_number(row['commits'])} |"
        )
    return '\n'.join(lines)


def main():
    now = datetime.now()

    available_years = sorted(
        [int(f.name.split('-')[0]) for f in Path('data').glob('[0-9][0-9][0-9][0-9]-volto-team-stats.csv')],
        reverse=True
    )

    if not available_years:
        print("No volto-team-stats CSV files found in data/!")
        return 1

    last_full_year = now.year - 1
    if last_full_year not in available_years:
        last_full_year = available_years[0]

    three_years = [y for y in available_years if y >= last_full_year - 2]
    all_years = available_years

    report = []
    report.append("# Volto Team Statistics Report")
    report.append("")
    report.append(f"Generated on: {now.strftime('%Y-%m-%d %H:%M:%S')}")
    report.append("")
    report.append(f"- **Available years**: {', '.join(map(str, available_years))}")
    report.append(f"- **Last full year**: {last_full_year}")
    report.append(f"- **3-year period**: {min(three_years)}-{max(three_years)}")
    report.append(f"- **All time**: {min(all_years)}-{max(all_years)}")
    report.append("")
    report.append("---")
    report.append("")

    periods = [
        (f"Last Full Year - {last_full_year}", [last_full_year]),
        (f"Past 3 Years: {min(three_years)}-{max(three_years)}", three_years),
        (f"All Time: {min(all_years)}-{max(all_years)}", all_years),
    ]

    for label, years in periods:
        df = combine(years)
        if df is not None:
            report.append(f"## Volto Team Contributors ({label})")
            report.append("")
            report.append(table(df))
            report.append("")
            report.append("")

    report.append("---")
    report.append("")
    report.append("## Notes")
    report.append("")
    report.append("- **PRs**: Pull requests submitted to plone/volto")
    report.append("- **Commits**: Direct commits to plone/volto")
    report.append("")
    report.append("Generated by Plone Contributor Statistics Tool")

    out = Path("report/volto-team.md")
    out.parent.mkdir(exist_ok=True)
    out.write_text('\n'.join(report))
    print(f"Report saved to {out}")
    return 0


if __name__ == "__main__":
    exit(main())
